/*
 * ORDS generated API for alarmasEventos
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AlarmasEventosItem struct {

	VEnveCodi string `json:"v_enve_codi,omitempty"`

	VEvenEstado string `json:"v_even_estado,omitempty"`

	VEvenEstaNuevo string `json:"v_even_esta_nuevo,omitempty"`

	VObse string `json:"v_obse,omitempty"`

	VFech string `json:"v_fech,omitempty"`

	VClprCodi string `json:"v_clpr_codi,omitempty"`
}
